version: '3'

services:
  ocs:
    image: cmotta2016/ocsinventory
    environment:
      OCS_DBNAME: ocsdatabase
      OCS_DBSERVER_READ: database
      OCS_DBSERVER_WRITE: database
      OCS_DBUSER: ocsuser
      OCS_DBPASS: ocspasswd
    volumes:
      - ocsserver:/usr/share/ocsinventory-reports/
      - ocsserver:/etc/ocsinventory-reports/
      - ocsserver:/var/lib/ocsinventory-reports/
    ports:
      - "80"
      - "443"
    container_name: ocsinventory-server
        
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe.
      MYSQL_USER: ocsuser
      MYSQL_PASSWORD: ocspasswd
      MYSQL_DATABASE: ocsdatabase
    volumes:
      - database:/var/lib/mysql
    container_name: database

  glpi:
    image: cmotta2016/glpi
    ports:
      - "80"
    volumes:
      - glpiserver:/var/www/glpi
    container_name: glpi-server

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"
    container_name: proxy

volumes:
  database:
  ocsserver:
  glpiserver:
